Repository warpnet/salt-lint, pull requests merged in 2019-12, with the labels that each got.

#118 Add rule for new_line_at_end_of_file similar to `yamllint`
  saltlint/rules/NewLineAtEndOfFileRule.py
  tests/unit/TestNewLineAtEndOfFileRule.py
Labels: Priority: Low, Type: Enhancement

#130 Change optparse to argparse
  .pylintrc
  README.md
  saltlint/cli.py
  saltlint/config.py
Labels: Priority: High, Type: Enhancement

#139 Fix automated PyPi deployment in Travis configuration
  .travis.yml
Labels: Priority: Medium, Type: Bug
