Repository warpnet/salt-lint, pull requests merged in 2019-10, with the labels that each got.

#2 Update Jinja rules
  lib/saltlint/rules/JinjaStatementHasSpacesRule.py
  lib/saltlint/rules/JinjaVariableHasSpacesRule.py
  tests/unit/TestJinjaStatementHasSpaces.py
  tests/unit/TestJinjaVariableHasSpaces.py
Labels: enhancement

#3 Add unit test for testing skipped rules
  README.rst
  tests/unit/TestSkipRule.py
Labels: enhancement

#6 Add File Mode Quotation rule
  lib/saltlint/rules/FileModeQuotationRule.py
  tests/unit/TestFileModeQuotationRule.py
Labels: enhancement

#7 Update gitignore
  .gitignore
Labels: Hacktoberfest

#9 Update versions
  lib/saltlint/rules/FileModeLeadingZeroRule.py
  lib/saltlint/rules/FileModeQuotationRule.py
Labels: Hacktoberfest

#22 Automate PyPi release
  .travis.yml
Labels: enhancement

#31 Add YamlHasOctalValueRule
  lib/saltlint/rules/YamlHasOctalValueRule.py
  tests/unit/TestYamlHasOctalValueRule.py
Labels: enhancement

#53 Update CONTRIBITING.md to use develop branch
  CONTRIBUTING.md
Labels: Priority: Low, Type: Enhancement

#54 Add option to run rules that use the full text
  lib/saltlint/__init__.py
Labels: Priority: Low, Type: Enhancement

#55 Refactor code for readability
  lib/saltlint/version.py
  saltlint/__init__.py
  saltlint/__main__.py
  saltlint/cli.py
  saltlint/formatters/__init__.py
  saltlint/linter.py
  saltlint/rules/FileExtensionRule.py
  saltlint/rules/FileModeLeadingZeroRule.py
  saltlint/rules/FileModeQuotationRule.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
  saltlint/rules/LineTooLongRule.py
  saltlint/rules/NoTabsRule.py
  saltlint/rules/TrailingWhitespaceRule.py
  saltlint/rules/YamlHasOctalValueRule.py
  saltlint/rules/__init__.py
  saltlint/utils.py
  setup.py
  tests/__init__.py
  tests/unit/TestFileExtension.py
  tests/unit/TestFileModeLeadingZeroRule.py
  tests/unit/TestFileModeQuotationRule.py
  tests/unit/TestJinjaCommentHasSpaces.py
  tests/unit/TestJinjaStatementHasSpaces.py
  tests/unit/TestJinjaVariableHasSpaces.py
  tests/unit/TestLineTooLong.py
  tests/unit/TestNoTabsRule.py
  tests/unit/TestSkipRule.py
  tests/unit/TestTrailingWhitespaceRule.py
  tests/unit/TestYamlHasOctalValueRule.py
Labels: Priority: Low, Type: Enhancement

#56 Add coverage reporting
  README.rst
  tox.ini
Labels: Priority: Low, Type: Maintenance

#65 Update documentation
  README.md
  README.rst
  setup.py
Labels: Type: Enhancement

#66 Update documentation
  .travis.yml
  CONTRIBUTING.md
  README.md
  README.rst
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  setup.py
  tests/unit/TestJinjaPillarGrainsGetFormatRule.py
Labels: Priority: High, Type: Maintenance

#67 Add config option to ingore rules per file
  saltlint/cli.py
  saltlint/config.py
  saltlint/linter.py
  saltlint/utils.py
  setup.py
  tests/__init__.py
  tests/unit/TestConfig.py
  tests/unit/TestFileExtension.py
  tests/unit/TestRunner.py
Labels: Type: Enhancement

#69 Fix 210 to skip non-number values
  saltlint/rules/YamlHasOctalValueRule.py
  tests/unit/TestYamlHasOctalValueRule.py
Labels: Priority: High, Type: Bug

#71 Version 0.0.10 Release
  saltlint/__init__.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
Labels: Type: Maintenance

#82 Update README.md to include list of rules
  README.md
Labels: Type: Enhancement

#84 Fix encoding to use utf-8
  saltlint/cli.py
Labels: Type: Bug

#81 Add JSON Formatter
  README.md
  saltlint/cli.py
  saltlint/config.py
  saltlint/formatters/__init__.py
Labels: Priority: Low, Type: Enhancement
