Repository warpnet/salt-lint, pull requests merged in 2019-11, with the labels that each got.

#88 Change all 'Salt state' occurrences to 'Salt State'
  README.md
Labels: Type: Enhancement

#90 Version 0.1.0 Release
  LICENSE
  docker/Dockerfile
  saltlint/__init__.py
  saltlint/rules/NoIrregularSpacesRule.py
Labels: Type: Maintenance

#91 Version 0.1.0 Release
  .travis.yml
  LICENSE
  README.md
  docker/Dockerfile
  saltlint/__init__.py
  saltlint/cli.py
  saltlint/config.py
  saltlint/formatters/__init__.py
  saltlint/rules/NoIrregularSpacesRule.py
Labels: Type: Maintenance

#94 Changed copyright
  saltlint/__main__.py
  saltlint/cli.py
  saltlint/config.py
  saltlint/formatters/__init__.py
  saltlint/linter.py
  saltlint/rules/FileExtensionRule.py
  saltlint/rules/FileModeLeadingZeroRule.py
  saltlint/rules/FileModeQuotationRule.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
  saltlint/rules/LineTooLongRule.py
  saltlint/rules/NoTabsRule.py
  saltlint/rules/TrailingWhitespaceRule.py
  saltlint/rules/YamlHasOctalValueRule.py
  saltlint/utils.py
  tests/__init__.py
  tests/unit/TestConfig.py
  tests/unit/TestFileExtension.py
  tests/unit/TestFileModeLeadingZeroRule.py
  tests/unit/TestFileModeQuotationRule.py
  tests/unit/TestJinjaCommentHasSpaces.py
  tests/unit/TestJinjaPillarGrainsGetFormatRule.py
  tests/unit/TestJinjaStatementHasSpaces.py
  tests/unit/TestJinjaVariableHasSpaces.py
  tests/unit/TestLineTooLong.py
  tests/unit/TestNoTabsRule.py
  tests/unit/TestRunner.py
  tests/unit/TestSkipRule.py
  tests/unit/TestTrailingWhitespaceRule.py
  tests/unit/TestYamlHasOctalValueRule.py
Labels: Type: Maintenance

#95 Add Python 3.8 job to Travis CI
  .coveragerc
  .travis.yml
  test-deps.txt
  tox.ini
Labels: Priority: Low, Type: Maintenance

#98 Update README
  README.md
Labels: Type: Documentation

#103 Fix typos in saltlint/linter.py
  saltlint/linter.py
Labels: Priority: Low, Type: Enhancement

#109 Update documentation
  README.md
Labels: Type: Documentation

#112 Json parameter now works in config file
  saltlint/config.py
Labels: Type: Enhancement

#113 Update CLI options to support British English
  saltlint/cli.py
Labels: Priority: Low, Type: Enhancement

#111 Add severity to standard output. Fixes #93
  README.md
  saltlint/cli.py
  saltlint/config.py
  saltlint/formatters/__init__.py
Labels: Priority: Low, Type: Enhancement

#121 Version 0.2.0 Release
  .coveragerc
  .travis.yml
  README.md
  docker/Dockerfile
  saltlint/__init__.py
  saltlint/__main__.py
  saltlint/cli.py
  saltlint/config.py
  saltlint/formatters/__init__.py
  saltlint/linter.py
  saltlint/rules/FileExtensionRule.py
  saltlint/rules/FileModeLeadingZeroRule.py
  saltlint/rules/FileModeQuotationRule.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
  saltlint/rules/LineTooLongRule.py
  saltlint/rules/NoTabsRule.py
  saltlint/rules/TrailingWhitespaceRule.py
  saltlint/rules/YamlHasOctalValueRule.py
  saltlint/utils.py
  test-deps.txt
  tests/__init__.py
  tests/unit/TestConfig.py
  tests/unit/TestFileExtension.py
  tests/unit/TestFileModeLeadingZeroRule.py
  tests/unit/TestFileModeQuotationRule.py
  tests/unit/TestJinjaCommentHasSpaces.py
  tests/unit/TestJinjaPillarGrainsGetFormatRule.py
  tests/unit/TestJinjaStatementHasSpaces.py
  tests/unit/TestJinjaVariableHasSpaces.py
  tests/unit/TestLineTooLong.py
  tests/unit/TestNoTabsRule.py
  tests/unit/TestRunner.py
  tests/unit/TestSkipRule.py
  tests/unit/TestTrailingWhitespaceRule.py
  tests/unit/TestYamlHasOctalValueRule.py
  tox.ini
Labels: Type: Maintenance

#125 Fix codespell issues
  .travis.yml
  README.md
  saltlint/cli.py
  saltlint/config.py
  tests/unit/TestConfig.py
Labels: Priority: Low, Type: Enhancement

#131 Fix some more pylint
  .pylintrc
  .travis.yml
  saltlint/cli.py
  saltlint/config.py
  saltlint/formatters/__init__.py
  saltlint/linter.py
  saltlint/rules/FileExtensionRule.py
  saltlint/rules/FileModeLeadingZeroRule.py
  saltlint/rules/FileModeQuotationRule.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
  saltlint/rules/LineTooLongRule.py
  saltlint/rules/NoIrregularSpacesRule.py
  saltlint/rules/NoTabsRule.py
  saltlint/rules/TrailingWhitespaceRule.py
  saltlint/rules/YamlHasOctalValueRule.py
  tests/__init__.py
Labels: Priority: Low, Type: Enhancement

#126 Change exclude path(s) to use pathspec
  saltlint/cli.py
  saltlint/config.py
  saltlint/linter.py
Labels: Priority: Low, Type: Enhancement

#133 Fix configuration test after introducing pathspec
  tests/unit/TestConfig.py
Labels: Priority: High, Type: Bug

#134 Update list() to [] and dict() to {}
  saltlint/cli.py
  saltlint/config.py
  saltlint/linter.py
  tests/unit/TestConfig.py
Labels: Priority: Low, Type: Enhancement
