Repository warpnet/salt-lint, pull requests merged in 2020-12, with the labels that each got.

#210 Merge develop into master
  README.md
  saltlint/linter/rule.py
  saltlint/linter/runner.py
  saltlint/rules/CmdRunQuietRule.py
  saltlint/rules/CmdWaitRecommendRule.py
  saltlint/rules/FileExtensionRule.py
  saltlint/rules/FileModeLeadingZeroRule.py
  saltlint/rules/FileModeQuotationRule.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
  saltlint/rules/NoTabsRule.py
  saltlint/rules/SLSFileNameRule.py
  saltlint/rules/YamlHasOctalValueRule.py
  saltlint/utils.py
  tests/__init__.py
  tests/test-extension-failure.extra.sls
  tests/unit/TestSLSFileNameRule.py
Labels: Type: Enhancement

#215 Only apply rule 214 on SLS files
  saltlint/rules/SLSFileNameRule.py
  tests/unit/TestSLSFileNameRule.py
  tests/unit/test-extension-failure.extra.jinja
Labels: Priority: High, Type: Bug

#214 Add new deprecation functionality
  saltlint/linter/rule.py
  saltlint/rules/CmdWaitRecommendRule.py
  saltlint/rules/StateDeprecationDockerAbsent.py
  saltlint/rules/StateDeprecationDockerImageAbsent.py
  saltlint/rules/StateDeprecationDockerImagePresent.py
  saltlint/rules/StateDeprecationDockerModWatch.py
  saltlint/rules/StateDeprecationDockerNetworkAbsent.py
  saltlint/rules/StateDeprecationDockerNetworkPresent.py
  saltlint/rules/StateDeprecationDockerRunning.py
  saltlint/rules/StateDeprecationDockerStopped.py
  saltlint/rules/StateDeprecationDockerVolumeAbsent.py
  saltlint/rules/StateDeprecationDockerVolumePresent.py
  saltlint/rules/StateDeprecationElasticsearchIndexRule.py
  saltlint/rules/StateDeprecationVirtRevertedRule.py
  saltlint/rules/StateDeprecationVirtSavedRule.py
  saltlint/rules/StateDeprecationVirtUnpoweredRule.py
  tests/unit/TestDeprecationRule.py
Labels: Priority: Low, Type: Enhancement
