Repository warpnet/salt-lint, pull requests merged in 2020-07, with the labels that each got.

#149 Update CI to Github actions
  .flake8
  .github/workflows/actions.yml
  .travis.yml
  README.md
  test-deps.txt
Labels: Priority: Low, Type: Enhancement

#150 Fix Dockerfile for salt-lint for version 0.3.0
  docker/Dockerfile
Labels: Priority: Low, Type: Maintenance

#153 Add Docker linting
  .github/workflows/lint.yml
Labels: Priority: Low, Type: Enhancement

#156 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Priority: Low, Type: Documentation

#155 Add Code of Conduct to the project
  CODE_OF_CONDUCT.md
Labels: Priority: Low, Type: Documentation

#154 Add demo to README.md
  README.md
  demo.gif
Labels: Priority: Low, Type: Documentation

#158 Fix spelling issues found by codespell
  README.md
  saltlint/cli.py
  saltlint/config.py
  tests/unit/TestConfig.py
Labels: Priority: Low, Type: Enhancement

#159 Update list() and dict() entries
  saltlint/cli.py
  saltlint/config.py
  saltlint/linter.py
Labels: Priority: Low, Type: Enhancement

#160 Fix code issues found by pylint
  saltlint/cli.py
  saltlint/config.py
  saltlint/formatters/__init__.py
  saltlint/linter.py
  saltlint/rules/FileExtensionRule.py
  saltlint/rules/FileModeLeadingZeroRule.py
  saltlint/rules/FileModeQuotationRule.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
  saltlint/rules/YamlHasOctalValueRule.py
  tests/unit/TestConfig.py
  tests/unit/TestRunner.py
  tests/unit/TestSkipRule.py
Labels: Priority: Low, Type: Enhancement

#173 Automate PyPi release using GitHub Actions
  .github/workflows/publish-to-pypi.yml
Labels: Priority: Medium, Type: Enhancement

#175 Only publish build on tags to prevent duplicate releases
  .github/workflows/publish-to-pypi.yml
Labels: Priority: Low, Type: Enhancement

#178 Replace optparse by argparse
  .github/workflows/lint.yml
  README.md
  saltlint/cli.py
Labels: Priority: Low, Type: Enhancement
