Repository warpnet/salt-lint, pull requests merged in 2021-01, with the labels that each got.

#218 Update supported Python versions
  .github/workflows/build.yml
  saltlint/formatters/__init__.py
  saltlint/rules/FileManagedReplaceContentRule.py
  saltlint/utils.py
  setup.py
Labels: Priority: Low, Type: Maintenance

#221 Use tox and pre-commit for testing
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tox.yml
  .gitignore
  .markdownlint.yaml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .pylintrc
  README.md
  pytest.ini
  test-requirements.txt
  tests/__init__.py
  tests/unit/TestNoIrregularSpacesRule.py
  tox.ini
Labels: Priority: Low, Type: Enhancement

#220 Add .j2 as Jinja file extension
  saltlint/utils.py
Labels: Priority: Low, Type: Enhancement

#219 Temporary remove rule 215 to prevent false positives
  README.md
  saltlint/rules/FileManagedReplaceContentRule.py
  tests/unit/TestFileManagedReplaceContentRule.py
Labels: Priority: Medium, Type: Bug

#223 Add CHANGELOG.md
  CHANGELOG.md
  setup.py
Labels: Priority: Low, Type: Documentation

#224 Add initial documentation
  .flake8
  .pre-commit-config.yaml
  .pylintrc
  .readthedocs.yml
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
Labels: Priority: Low, Type: Documentation

#225 Remove rule 801
  README.md
  saltlint/rules/CronStateHasIdentifierRule.py
  tests/unit/TestCmdRunQuietRule.py
  tests/unit/TestCronStateHasIdentifierRule.py
Labels: Priority: Medium, Type: Bug

#229 Bump version to 0.5.0
  .readthedocs.yml
  docs/contributing.rst
  saltlint/__init__.py
Labels: Priority: Medium, Type: Maintenance

#231 fix: ensure all excluded paths are included
  CHANGELOG.md
  saltlint/linter/runner.py
  tests/unit/TestRunner.py
Labels: Priority: High, Type: Bug

#233 chore: bump version to 0.5.1
  CHANGELOG.md
  README.md
  saltlint/__init__.py
Labels: Priority: High, Type: Maintenance

#234 fix: append changelog to long description in setup.py
  CHANGELOG.md
  MANIFEST.in
  setup.py
Labels: Priority: Low, Type: Bug

#235 Update documentation
  README.md
Labels: Priority: Low, Type: Documentation

#236 fix: ignore Jinja rules in Jinja escaped blocks
  CHANGELOG.md
  saltlint/linter/rule.py
  saltlint/rules/JinjaCommentHasSpacesRule.py
  saltlint/rules/JinjaPillarGrainsGetFormatRule.py
  saltlint/rules/JinjaStatementHasSpacesRule.py
  saltlint/rules/JinjaVariableHasSpacesRule.py
  tests/unit/TestJinjaCommentHasSpaces.py
  tests/unit/TestJinjaStatementHasSpaces.py
  tests/unit/TestJinjaVariableHasSpaces.py
Labels: Priority: High, Type: Bug

#238 chore: bump version to v0.5.2
  CHANGELOG.md
  saltlint/__init__.py
Labels: Priority: Low, Type: Maintenance

#239 chore: drop Python 2.7 support
  .github/workflows/tox.yml
  CHANGELOG.md
  saltlint/__main__.py
  saltlint/cli.py
  saltlint/config.py
  saltlint/linter/collection.py
  saltlint/linter/rule.py
  saltlint/linter/runner.py
  setup.py
  tox.ini
Labels: Priority: Low, Type: Maintenance

#241 test: add type hint test using mypy
  .github/workflows/tox.yml
  saltlint/config.py
  saltlint/linter/rule.py
  tox.ini
Labels: Priority: Low, Type: Enhancement

#245 Update documentation
  docs/index.md
Labels: Priority: Low, Type: Documentation
