Repository warpnet/salt-lint, pull requests merged in 2021-11, with the labels that each got.

#270 Added manpage for salt-lint
  docs/man/salt-lint.1
Labels: Type: Documentation

#271 Bump version to v0.7.0
  CHANGELOG.md
  docs/index.md
  docs/man/salt-lint.1
  saltlint/__init__.py
Labels: Type: Maintenance, Priority: Low

#272 Fix false positive for spaces in Jinja variable
  CHANGELOG.md
  saltlint/rules/JinjaVariableHasSpacesRule.py
  tests/unit/TestJinjaVariableHasSpaces.py
Labels: Type: Bug

#274 Ignore non file mode lines in rule 207 and 208
  .pylintrc
  CHANGELOG.md
  saltlint/rules/FileModeLeadingZeroRule.py
  saltlint/rules/FileModeQuotationRule.py
  tests/unit/TestFileModeLeadingZeroRule.py
  tests/unit/TestFileModeQuotationRule.py
Labels: Type: Bug

#275 Bump version to v0.8.0
  CHANGELOG.md
  docs/man/salt-lint.1
  saltlint/__init__.py
Labels: Type: Maintenance
