Repository warpnet/salt-lint, pull requests merged in 2023-01, with the labels that each got.

#291 fix: python linting issues
  .pylintrc
  saltlint/config.py
  saltlint/formatters/default.py
  saltlint/formatters/severity.py
  saltlint/linter/match.py
  saltlint/rules/NoIrregularSpacesRule.py
Labels: Type: Maintenance, Priority: Low

#292 fix(docs): pre-commit configuration example
  docs/index.md
Labels: Priority: Low, Type: Documentation

#294 Fix pylint issues
  setup.py
  tests/unit/TestNoIrregularSpacesRule.py
Labels: Type: Maintenance, Priority: Low

#295 Add missing entries to changelog
  CHANGELOG.md
Labels: Priority: Low, Type: Documentation

#300 rev(rule210): Resolve causing a lot of false positives
  CHANGELOG.md
  saltlint/__init__.py
  saltlint/rules/YamlHasOctalValueRule.py
  tests/unit/TestYamlHasOctalValueRule.py
Labels: Type: Bug, Priority: High
